import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers":
        "authorization, x-client-info, apikey, content-type",
        }

        const CK_USER_ID = "CK3465"
        const CK_API_KEY = "883X7UC8QL53767968HJ778Y657VF5G2G0N21O361NDVBBOLWI73RDTFC365SFDU"

        serve(async (req) => {
          if (req.method === "OPTIONS") {
              return new Response("ok", { headers: corsHeaders })
                }

                  try {
                      const body = await req.json()
                          const { action } = body

                              // ==============================
                                  // GET DATA PLANS
                                      // ==============================
                                          if (action === "get_plans") {
                                                const url = `https://www.nellobytesystems.com/APIDatabundlePlansV2.asp?UserID=${CK_USER_ID}`

                                                      const response = await fetch(url)
                                                            const rawText = await response.text()

                                                                  let json: any
                                                                        try {
                                                                                json = JSON.parse(rawText)
                                                                                      } catch {
                                                                                              return new Response(
                                                                                                        JSON.stringify({ success: false, error: "Invalid JSON from provider" }),
                                                                                                                  { headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                          )
                                                                                                                                }

                                                                                                                                      const networks = json?.MOBILE_NETWORK || {}

                                                                                                                                            const extractPlans = (networkArr: any[] = []) => {
                                                                                                                                                    if (!Array.isArray(networkArr)) return []

                                                                                                                                                            return networkArr.flatMap((n) => {
                                                                                                                                                                      if (!Array.isArray(n.PRODUCT)) return []

                                                                                                                                                                                return n.PRODUCT.map((p: any) => ({
                                                                                                                                                                                            id: String(p.PRODUCT_CODE),
                                                                                                                                                                                                        name: String(p.PRODUCT_NAME),
                                                                                                                                                                                                                    price: Number(p.PRODUCT_AMOUNT),
                                                                                                                                                                                                                                raw: p,
                                                                                                                                                                                                                                          }))
                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                              const normalized = {
                                                                                                                                                                                                                                                                      MTN: extractPlans(networks.MTN),
                                                                                                                                                                                                                                                                              GLO: extractPlans(networks.Glo),
                                                                                                                                                                                                                                                                                      AIRTEL: extractPlans(networks.Airtel),
                                                                                                                                                                                                                                                                                              ETISALAT: extractPlans(networks["9mobile"]),
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                          return new Response(
                                                                                                                                                                                                                                                                                                                  JSON.stringify({ success: true, networks: normalized }),
                                                                                                                                                                                                                                                                                                                          { headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        // ==============================
                                                                                                                                                                                                                                                                                                                                            // BUY DATA ✅ FIXED PROPERLY
                                                                                                                                                                                                                                                                                                                                                // ==============================
                                                                                                                                                                                                                                                                                                                                                    if (action === "buy_data") {
                                                                                                                                                                                                                                                                                                                                                          const { networkCode, mobileNumber, planId, requestId } = body
                                                                                                                                                                                                                                                                                                                                                                const reqID = requestId || `REQ_${Date.now()}`

                                                                                                                                                                                                                                                                                                                                                                      // 🚨 V2 USES Network + PhoneNumber
                                                                                                                                                                                                                                                                                                                                                                            const buyUrl =
                                                                                                                                                                                                                                                                                                                                                                                    `https://www.nellobytesystems.com/APIDatabundleV2.asp` +
                                                                                                                                                                                                                                                                                                                                                                                            `?UserID=${CK_USER_ID}` +
                                                                                                                                                                                                                                                                                                                                                                                                    `&APIKey=${CK_API_KEY}` +
                                                                                                                                                                                                                                                                                                                                                                                                            `&Network=${networkCode}` +
                                                                                                                                                                                                                                                                                                                                                                                                                    `&DataPlan=${planId}` +
                                                                                                                                                                                                                                                                                                                                                                                                                            `&PhoneNumber=${mobileNumber}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                    `&RequestID=${reqID}`

                                                                                                                                                                                                                                                                                                                                                                                                                                          const response = await fetch(buyUrl)
                                                                                                                                                                                                                                                                                                                                                                                                                                                const rawText = await response.text()

                                                                                                                                                                                                                                                                                                                                                                                                                                                      let result: any
                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = JSON.parse(rawText)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  result = { status: rawText }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(JSON.stringify(result), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: { ...corsHeaders, "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // BUY AIRTIME (UNCHANGED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (action === "buy_airtime") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { networkCode, mobileNumber, amount, requestId } = body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const reqID = requestId || `REQ_${Date.now()}`

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const airtimeUrl =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `https://www.nellobytesystems.com/APIAirtimeV1.asp` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `?UserID=${CK_USER_ID}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `&APIKey=${CK_API_KEY}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `&MobileNetwork=${networkCode}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `&Amount=${amount}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `&MobileNumber=${mobileNumber}` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `&RequestID=${reqID}`

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await fetch(airtimeUrl)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const rawText = await response.text()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let result: any
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          result = JSON.parse(rawText)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result = { status: rawText }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(JSON.stringify(result), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { ...corsHeaders, "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JSON.stringify({ success: false, error: "Invalid action" }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 400 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify({ success: false, error: error.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })